#version: '3.9'
#
#services:
#  db:
#    image: 'postgres'
#    ports:
#      - '2345:5432'
#    environment:
#      POSTGRES_USER: 'postgres'
#      POSTGRES_PASSWORD: 'password'
#      POSTGRES_DB: 'test'
#  server:
#    build: .
#    ports:
#      - '5000:5000'
#    environment:
#      DATABASE_URL: 'postgresql://postgres:password@db:5432/test?schema=public'

version: '3.9'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '2345:5432'
volumes:
  postgres: