// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NavBar: typeof import('./src/app/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectMenu: typeof import('./src/app/components/SelectMenu.vue')['default']
    ToDoListSideBar: typeof import('./src/app/components/ToDoListSideBar.vue')['default']
    ToDoMenu: typeof import('./src/app/components/ToDoMenu.vue')['default']
    ToDoTasks: typeof import('./src/app/components/ToDoTasks.vue')['default']
  }
}
